// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuDwSPgsmB-2C0Glb8Rpr7tZDj89STap8',
    appId: '1:752692642868:web:944aa317210dc789b67661',
    messagingSenderId: '752692642868',
    projectId: 'balancedmeal-f2ec8',
    authDomain: 'balancedmeal-f2ec8.firebaseapp.com',
    storageBucket: 'balancedmeal-f2ec8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm5vZkEzFDU3H5I6LBIET6HfVFTH8dk04',
    appId: '1:752692642868:android:2c2efb53c25826ebb67661',
    messagingSenderId: '752692642868',
    projectId: 'balancedmeal-f2ec8',
    storageBucket: 'balancedmeal-f2ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvrfkff_oXMDYbdBx9BgtYdCsTe7ig3c',
    appId: '1:752692642868:ios:5ec92e24f528a2b0b67661',
    messagingSenderId: '752692642868',
    projectId: 'balancedmeal-f2ec8',
    storageBucket: 'balancedmeal-f2ec8.firebasestorage.app',
    iosBundleId: 'com.example.balancedmeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvrfkff_oXMDYbdBx9BgtYdCsTe7ig3c',
    appId: '1:752692642868:ios:5ec92e24f528a2b0b67661',
    messagingSenderId: '752692642868',
    projectId: 'balancedmeal-f2ec8',
    storageBucket: 'balancedmeal-f2ec8.firebasestorage.app',
    iosBundleId: 'com.example.balancedmeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuDwSPgsmB-2C0Glb8Rpr7tZDj89STap8',
    appId: '1:752692642868:web:b2c8af300444288bb67661',
    messagingSenderId: '752692642868',
    projectId: 'balancedmeal-f2ec8',
    authDomain: 'balancedmeal-f2ec8.firebaseapp.com',
    storageBucket: 'balancedmeal-f2ec8.firebasestorage.app',
  );
}
